version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - ./data:/var/lib/clickhouse/
      - ./logs:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"